### Attention

In [1]:
import torch

- B - batch_size
- T - token_size  (context_size)
- C - embedding_size

In [2]:
torch.manual_seed(123)
B, T, C = 4, 8, 32
head_size = 16

x = torch.rand(B, T, C)
x.shape

torch.Size([4, 8, 32])

In [3]:
query = torch.nn.Linear(C, head_size, bias=False)
key = torch.nn.Linear(C, head_size, bias=False)
value = torch.nn.Linear(C, head_size, bias=False)

In [4]:
q = query(x)  # shape(B, T, head_size)
k = key(x)  # shape(B, T, head_size)
v = value(x)  # shape(B, T, head_size)

In [5]:
q.shape, k.shape, v.shape

(torch.Size([4, 8, 16]), torch.Size([4, 8, 16]), torch.Size([4, 8, 16]))

In [6]:
k.shape, k.transpose(-2, -1).shape
# k.T.shape 

(torch.Size([4, 8, 16]), torch.Size([4, 16, 8]))

In [7]:
q # [4, 8, 16] @ [4, 16, 8] --> [4, 8, 8]

tensor([[[ 2.0380e-02, -2.2876e-01, -1.2514e-03, -2.2801e-01,  1.5430e-01,
          -3.6612e-01, -2.5370e-02, -8.8679e-02,  1.9030e-02, -3.9732e-01,
           1.8314e-01,  4.0095e-01, -3.5058e-01,  7.0763e-01, -2.4651e-01,
           3.8136e-02],
         [ 3.8563e-02, -4.4865e-02,  2.5996e-01, -2.0992e-02,  1.4343e-01,
          -2.0800e-01, -2.8579e-01,  2.4478e-01, -5.7314e-02, -2.2519e-01,
           2.1202e-01,  6.3992e-01, -8.2448e-01,  6.0475e-01,  1.6443e-01,
           3.1349e-01],
         [ 2.4900e-01, -2.0065e-01,  2.7512e-01,  9.3881e-02,  2.6198e-01,
          -5.0754e-01, -2.4272e-01,  2.2742e-01, -5.0962e-02, -3.0973e-01,
           2.5404e-01,  7.6782e-01, -6.2676e-01,  5.6041e-01, -2.4566e-01,
           2.2742e-02],
         [ 4.1481e-01,  1.1574e-01,  2.0226e-01,  3.0846e-01,  1.6567e-01,
          -6.4875e-01, -2.4685e-01,  1.4867e-02, -1.7268e-01, -2.2497e-01,
           9.6643e-02,  6.8220e-01, -6.0833e-01,  4.8628e-02, -2.1982e-01,
          -1.0156e-02],
    

In [8]:
atten_score = torch.matmul(q, k.transpose(-2, -1))
atten_score.shape

atten_weights = torch.softmax(atten_score/k.shape[-1]**0.5, dim=-1)
atten_weights[0][5].sum()

tensor(1.0000, grad_fn=<SumBackward0>)

In [9]:
atten_weights = torch.softmax(atten_score, dim=-1)
atten_weights[0][5]

tensor([0.1354, 0.1319, 0.1198, 0.1167, 0.1061, 0.1207, 0.0982, 0.1712],
       grad_fn=<SelectBackward0>)

In [10]:
atten_score[0, 5]

tensor([-0.0805, -0.1069, -0.2030, -0.2298, -0.3244, -0.1957, -0.4023,  0.1540],
       grad_fn=<SelectBackward0>)

In [11]:
koyil = atten_score[0, 5]
torch.softmax(koyil, -1)

tensor([0.1354, 0.1319, 0.1198, 0.1167, 0.1061, 0.1207, 0.0982, 0.1712],
       grad_fn=<SoftmaxBackward0>)

In [12]:
koyil = torch.Tensor([0.2, 0.7, 0.04, 0.11]) # / 4**0.5
torch.softmax(koyil, -1)

tensor([0.2265, 0.3735, 0.1930, 0.2070])

In [13]:
torch.rand(2, 3, 3)@torch.rand(2, 3, 3)

tensor([[[0.5467, 0.4718, 0.3451],
         [0.8296, 1.1860, 1.2326],
         [0.0365, 0.0228, 0.0899]],

        [[0.7822, 0.8339, 0.6631],
         [0.3256, 0.8914, 0.8464],
         [1.2214, 1.5549, 1.5852]]])